POST http://localhost:4000/api/questions
Content-Type: application/json
Authorization: :Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksIm5hbWUiOiJBZG1pbiBJcmFqYW4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjM3NzY4NTJ9.GzSzcrF0EB-96lUxdzeCQtqIhk5rKkIWoTWGwr5XxZ4

{
    "content":"What is your name ?"

}


###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email":"example@admin.com",
    "password":"password1"
}
